cmake_minimum_required(VERSION 3.22)
project(SkyInstrumentQOhos VERSION 6.12.0 LANGUAGES C CXX)
set(QT_SKIP_AUTO_PLUGIN_INCLUSION ON)
set(QT_GENERATE_SBOM OFF)
set(QT_GENERATE_SOURCE_SBOM OFF)
find_package(Qt6 6.12.0 EXACT REQUIRED COMPONENTS BuildInternals)
qt_internal_project_setup()
find_package(Qt6 6.12.0 EXACT REQUIRED COMPONENTS Core CorePrivate Gui GuiPrivate OpenGL OpenGLPrivate)
qt_build_internals_set_up_private_api()
list(PREPEND CMAKE_MODULE_PATH "${QTBASE_SOURCE}/cmake")
find_package(NodeAddonApi REQUIRED)
find_package(Fontconfig REQUIRED)
set(QT_QPA_PLATFORMS ohos)
add_subdirectory("${QTBASE_SOURCE}/src/plugins/platforms/ohos" platform)
